// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarCompanyBilling.Models.DataLayer
{
    public partial class Customer
    {
        public Customer()
        {
            SalesInvoices = new HashSet<SalesInvoice>();
        }

        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }

        public virtual Zip ZipNavigation { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
    }
}