// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarCompanyBilling.Models
{
    public partial class Employee
    {
        public Employee()
        {
            SalesInvoices = new HashSet<SalesInvoice>();
        }

        public decimal EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public DateTime? BirthDate { get; set; }
        public decimal SocSecNo { get; set; }
        public DateTime HireDate { get; set; }
        public decimal? WorkDeptId { get; set; }
        public decimal? JobId { get; set; }
        public decimal? Salary { get; set; }
        public decimal? Bonus { get; set; }
        public decimal? Commission { get; set; }

        public virtual Job Job { get; set; }
        public virtual Department WorkDept { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
    }
}