// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarCompanyBilling.Models
{
    public partial class Part
    {
        public decimal CarId { get; set; }
        public decimal VendorId { get; set; }
        public string PartDescription { get; set; }
        public decimal PartCost { get; set; }

        public virtual Car Car { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}