// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarCompanyBilling.Models
{
    public partial class SalesInvoice
    {
        public int InvoiceId { get; set; }
        public DateTime Date { get; set; }
        public decimal Price { get; set; }
        public decimal OnRoadPrice { get; set; }
        public decimal CarId { get; set; }
        public int CustomerId { get; set; }
        public decimal SalespersonId { get; set; }
        public string VinNumber { get; set; }

        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Salesperson { get; set; }
    }
}