// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarCompanyBilling.Models
{
    public partial class Vendor
    {
        public Vendor()
        {
            Parts = new HashSet<Part>();
        }

        public decimal VendorId { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }

        public virtual ICollection<Part> Parts { get; set; }
    }
}