// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarCompanyBilling.Models
{
    public partial class Warehouse
    {
        public Warehouse()
        {
            Inventories = new HashSet<Inventory>();
        }

        public decimal WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string Location { get; set; }

        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}